document.writeln("<div class=\"homeNav2\">");
document.writeln("<ul>");
document.writeln("<li><a href=\"/Popular_American_English/\">流行美语</a></li>");
document.writeln("<li><a href=\"/oral/jingjixuerenshuangyuban/\">经济学人</a></li>");
document.writeln("<li><a href=\"/oral/PBS/\">高端访谈</a></li>");
document.writeln("<li><a href=\"/News-Plus-Special-English/\">NEWSPlus</a></li>");
document.writeln("<li><a href=\"/FOX-NEWS/\">FOX NEWS</a></li>");
document.writeln("<li><a href=\"/Business-Etiquette/\">礼节美语</a></li>");
document.writeln("<li><a href=\"/Learn-a-Word/\">学个词</a></li>");
document.writeln("<li><a href=\"/yingyuriji/\">英语日记</a></li>");
document.writeln("<li><a href=\"/yingyushige/\">英语诗歌</a></li>");
document.writeln("<li><a href=\"/yingyumiyu/\">英语谜语</a></li>");
document.writeln("<li><a href=\"/yingyuyanyu/\">英语谚语</a></li>");
document.writeln("<li><a href=\"/zhufu/\">祝福赠言</a></li>");
document.writeln("<li><a href=\"/yingyuxiaogushi/\">英语故事</a></li>");
document.writeln("<li><a href=\"/mingxiaogongkaike/\">公开课</a></li>");
document.writeln("<li><a href=\"/yingwenaiqingshi/\">英文诗</a></li>");
document.writeln("</ul>");
document.writeln("</div>");