document.writeln("<script async src=\"\/\/pagead2.googlesyndication.com\/pagead\/js\/adsbygoogle.js\"><\/script>");
document.writeln("<!-- m_show_300_300.js -->");
document.writeln("<ins class=\"adsbygoogle\"");
document.writeln("     style=\"display:block\"");
document.writeln("     data-ad-client=\"ca-pub-1903766104757163\"");
document.writeln("     data-ad-slot=\"5853206198\"");
document.writeln("     data-ad-format=\"auto\"><\/ins>");
document.writeln("<script>");
document.writeln("(adsbygoogle = window.adsbygoogle || []).push({});");
document.writeln("<\/script> ");

document.writeln("<script async src=\'//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\'></script>");
document.writeln("<ins class=\'adsbygoogle\'");
document.writeln("     style=\'display:block; text-align:center;\'");
document.writeln("     data-ad-format=\'fluid\'");
document.writeln("     data-ad-layout=\'in-article\'");
document.writeln("     data-ad-client=\'ca-pub-1903766104757163\'");
document.writeln("     data-ad-slot=\'2952456236\'></ins>");
document.writeln("<script>");
document.writeln("     (adsbygoogle = window.adsbygoogle || []).push({});");
document.writeln("</script>");