document.writeln("<script async src=\"\/\/pagead2.googlesyndication.com\/pagead\/js\/adsbygoogle.js\"><\/script>");
document.writeln("<!-- m_show_300_300.js -->");
document.writeln("<ins class=\"adsbygoogle\"");
document.writeln("     style=\"display:block\"");
document.writeln("     data-ad-client=\"ca-pub-1903766104757163\"");
document.writeln("     data-ad-slot=\"5853206198\"");
document.writeln("     data-ad-format=\"auto\"><\/ins>");
document.writeln("<script>");
document.writeln("(adsbygoogle = window.adsbygoogle || []).push({});");
document.writeln("<\/script> ");